<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Tosun Flux</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>..\assets\Tosun.ico</ApplicationIcon>
    <Version>0.3.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="..\assets\tosun-floating-v1.png" Link="Assets\tosun-floating-v1.png" />
    <Resource Include="..\assets\Tosun.ico" Link="Assets\Tosun.ico" />
    <Resource Include="..\assets\Pretendard.ttf" Link="Assets\Pretendard.ttf" />
  </ItemGroup>
</Project>
